name: Deploy React App to GitHub Pages


on:
  push:
    branches:
      - main


jobs:
    build-deploy:
        runs-on: ubuntu-latest

    steps:
      #Checkout the repository of github
      -name: Checkout code
       uses: actions/checkout@v3    

       #Setup Node.js env
      -name: Setup Node.js
       uses: actions/setup-node@v3
       with:
          node-version: 18

       #Intall all dependences
       -name : Install all dependencies
        run: npm install

        # Build the project
        -name : Build the project
         run: npm run build   

        # Deploy to Github pages
        -name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./dist 